#!/bin/bash


if [[ "${ASK_API_URL:-}" == "" ]]; then
  echo "Error: ASK_API_URL is not set."
  exit 1
fi

if [[ "${ASK_MODEL:-}" == "" ]]; then
  echo "Error: ASK_MODEL is not set."
  exit 1
fi

if [[ "${ASK_API_KEY:-}" == "" ]]; then
  echo "Error: ASK_API_KEY is not set."
  exit 1
fi

USER_PROMPT=""
if [ ! -t 0 ]; then
  USER_PROMPT=$(cat)
fi

if [ "$#" -gt 0 ]; then
  if [ -n "$USER_PROMPT" ]; then
    USER_PROMPT="$USER_PROMPT $*"
  else
    USER_PROMPT="$*"
  fi
fi

if [ -z "$USER_PROMPT" ]; then
  echo "Error: No prompt provided."
  exit 1
fi

echo "User prompt: $USER_PROMPT"

curl "$ASK_API_URL" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $ASK_API_KEY" \
-d '{
	"model": "'$ASK_MODEL'",
	"messages": [
	{
		"role": "system",
		"content": "You are a CLI tool. Output plain text only. No yapping. Keep the output concise."
	},
	{
		"role": "user",
		"content": "'"$USER_PROMPT"'"
	}]
}'
