#!/bin/bash

curl "$ASK_API_URL" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $ASK_API_KEY" \
-d '{
	"model": "llama-3.3-70b-versatile",
	"messages": [
	{
		"role": "system",
		"content": "You are a CLI tool. Output plain text only. No yapping. Keep the output concise."
	},
	{
		"role": "user",
		"content": "Explain the importance of fast language models"
	}]
}'
